[package]
name = "tere-rs"
version = "0.1.0"
authors = ["mgunyho <marci.gunyho@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#TODO: statically link everything... (possible?) -- see https://stackoverflow.com/a/31778003

[dependencies]
pancurses = { version = "0.16", features = ["wide"] }
ncurses = { version = "5.91" }
