[package]
name = "tere"
version = "0.0.10"
authors = ["mgunyho <marci.gunyho@gmail.com>"]
edition = "2018"
description = "A fast way to navigate folders in the terminal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#TODO: statically link everything... (possible?) -- see https://stackoverflow.com/a/31778003

[dependencies]
crossterm = "0.20.0"
dirs = "4.0.0"
regex = "1.5.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["rc"] }
textwrap = "0.14"
unicode-segmentation = "1.7"

[dependencies.clap]
version = "3"
features = ["wrap_help"]  # TODO: consider color?

[profile.release]
lto = true
