[package]
name = "tere"
version = "0.0.19"
authors = ["mgunyho <marci.gunyho@gmail.com>"]
edition = "2018"
description = "A fast way to navigate folders in the terminal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.24.0"
dirs = "4.0.0"
regex = "1.5.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["rc"] }
textwrap = "0.14"
unicode-segmentation = "1.7"

[dependencies.clap]
version = "3"
default-features = false
features = ["wrap_help", "suggestions", "std"]

[profile.release]
lto = true
strip = "debuginfo"
