[package]
name = "tere-rs"
version = "0.1.0"
authors = ["mgunyho <marci.gunyho@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#TODO: statically link everything... (possible?) -- see https://stackoverflow.com/a/31778003

[dependencies]
pancurses = { version = "0.16", features = ["wide"] }
ncurses = { version = "5.91" }
crossterm = "0.20.0"
home = "0.5.3"

[dependencies.clap]
version = "2"
features = ["wrap_help"]  # TODO: consider color?

[profile.release]
lto = true
