[package]
name = "tere"
version = "0.0.3"
authors = ["mgunyho <marci.gunyho@gmail.com>"]
edition = "2018"
description = "A fast way to navigate folders in the terminal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#TODO: statically link everything... (possible?) -- see https://stackoverflow.com/a/31778003

[dependencies]
crossterm = "0.20.0"
dirs = "4.0.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["rc"] }

[dependencies.clap]
version = "2"
features = ["wrap_help"]  # TODO: consider color?

[profile.release]
lto = true
